version: "3.0"
services:
  frontend:
    build: .
    image: rafipayment_frontend
    container_name: frontend
    environment:
      - NODE_ENV=production
    volumes:
      - rafipayment_frontend_data:/app/dist/
    ports:
      - 3737:8080
    command: ./build/build-production.sh
    deploy:
      restart_policy:
        condition: any

volumes:
  rafipayment_frontend_data:
    external: true

networks:
  default:
    external:
      name: rafipayment_network