version: "3.0"
services:
  frontend:
    build: .
    image: rafipayment_frontend
    container_name: frontend
    environment:
      - NODE_ENV=staging
    volumes:
      - rafipayment_frontend_data:/app/dist/
    ports:
      - 3737:8080
    command: npm run staging

volumes:
  rafipayment_frontend_data:
    external: true

networks:
  default:
    external:
      name: rafipayment_network