#!/usr/bin/python

import sys
import subprocess

from_commit, to_commit, ref = sys.stdin.read().strip("\n").split(" ")
branch = ref.split("/")[2]

print("Received branch {branch}, deploying!".format(branch=branch))
subprocess.call(["deploy", "frontend", "-f"])
